# Generated by Django 3.0.3 on 2020-02-29 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('venue', models.CharField(default=None, max_length=200)),
                ('department', models.CharField(default=None, max_length=100)),
                ('event_category', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None)),
                ('date_added', models.DateField()),
                ('event_date', models.DateTimeField(default=None)),
                ('end_date', models.DateTimeField(default=None)),
                ('event_status', models.PositiveIntegerField(choices=[(0, 'Closed'), (1, 'Open')], default='1')),
                ('techinical_event', models.TextField(default=None)),
                ('non_techinical_event', models.TextField(default=None)),
                ('reg_fee_in_rupees', models.PositiveIntegerField(default=0)),
                ('event_organizer_name', models.CharField(default=None, max_length=50)),
                ('event_organizer_contact', models.CharField(default=None, max_length=10)),
                ('event_booking_email', models.EmailField(max_length=254)),
                ('event_image', models.ImageField(blank=True, upload_to='image')),
                ('student_coordinator_name', models.CharField(default=None, max_length=100)),
                ('student_coordinator_mobile', models.CharField(default=None, max_length=10)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_status', models.PositiveIntegerField(choices=[(0, 'No, thanks'), (1, 'I may attend'), (2, "I'll be there")], default='0')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='events.Event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_partications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
