# Generated by Django 3.0.3 on 2020-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='department',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.PositiveIntegerField(choices=[(0, 'Department of IT'), (1, 'Department of CSE'), (2, 'Department of Mechanical'), (3, 'Department of ECE'), (4, 'Department of EEE'), (5, 'Department of Civil')], default='0'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reg_fee_in_rupees',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
