# Generated by Django 3.0.3 on 2020-05-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200521_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Department',
            field=models.PositiveIntegerField(choices=[(0, 'Department of IT'), (1, 'Department of CSE'), (2, 'Department of Mechanical'), (3, 'Department of ECE'), (4, 'Department of EEE'), (5, 'Department of Civil')], default='0'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.PositiveIntegerField(choices=[(0, 'Closed'), (1, 'Open')], default='1'),
        ),
    ]
